### ISSUE TITLE
Feature Request: Show where the points are coming from

### ISSUE THREAD

**Issue by josercruz01** [alphasights/lion-api#58]
Would be nice to see where the points came from on each week, a list of PR's and how many points per each PR, for instance:

Jose - 80 points
- 20 points for https://github.com/alphasights/octopus/pull/1021
- 60 points for https://github.com/alphasights/octopus/pull/1021

**Comment by delkopiso** [comment]
fixed by https://github.com/alphasights/lion-api/pull/84
