### ISSUE TITLE
Use the Review API to for better accuracy in determining who is the reviewer

### ISSUE THREAD

**Issue by daemonsy** [alphasights/lion-api#68]
Right now, I believe we use the first :+1: as a way of determining who is the reviewer. 

Since the concept of a reviewer is now formalized in Github, can we use the Review API to do it? Also if there are two reviewers, I guess the points should be split evenly :)

**Comment by delkopiso** [comment]
Github hasn't released a review API yet: https://developer.github.com/changes/2016-10-11-pull-request-review-webhooks/

**Comment by delkopiso** [comment]
Fixed in https://github.com/alphasights/lion-api/pull/81
